export const sagaActions = {
    FETCH_WEATHER_SAGA: 'FETCH_WEATHER_SAGA',
    FETCH_WEATHER_FAILURE: 'FETCH_WEATCHER_FAILURE',
    START_POLLING_SAGA: 'START_POLLING_SAGA',
    STOP_POLLING_SAGA: 'STOP_POLLING_SAGA',
};